import * as apigwv2 from "@aws-cdk/aws-apigatewayv2-alpha";
import * as apigwv2Authorizers from "@aws-cdk/aws-apigatewayv2-authorizers-alpha";
import * as apigwv2Integrations from "@aws-cdk/aws-apigatewayv2-integrations-alpha";
import * as cdk from "aws-cdk-lib";
import { Aspects } from "aws-cdk-lib";
import * as acm from "aws-cdk-lib/aws-certificatemanager";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import * as cloudwatchActions from "aws-cdk-lib/aws-cloudwatch-actions";
import * as codedeploy from "aws-cdk-lib/aws-codedeploy";
import * as events from "aws-cdk-lib/aws-events";
import * as eventsTargets from "aws-cdk-lib/aws-events-targets";
import * as iam from "aws-cdk-lib/aws-iam";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as lambdaNodejs from "aws-cdk-lib/aws-lambda-nodejs";
import * as route53 from "aws-cdk-lib/aws-route53";
import * as route53targets from "aws-cdk-lib/aws-route53-targets";
import type * as secretsmanager from "aws-cdk-lib/aws-secretsmanager";
import type * as sns from "aws-cdk-lib/aws-sns";
import * as wafv2 from "aws-cdk-lib/aws-wafv2";
import type { Construct } from "constructs";
import * as path from "path";
import { InternalRoutes } from "./routes/internal-routes";
import { ProtectedRoutes } from "./routes/protected-routes";
import { PublicRoutes } from "./routes/public-routes";
import { RouteBuilder } from "./routes/route-builder";
import { LogRetentionAspect } from "./utils/log-retention-aspect";

export interface ApiStackProps extends cdk.StackProps {
	stage: string;
	workosSecret: secretsmanager.Secret;
	dbSecret: secretsmanager.Secret;
	alarmTopic: sns.Topic;
}

export class ApiStack extends cdk.Stack {
	public readonly httpApi: apigwv2.HttpApi;

	constructor(scope: Construct, id: string, props: ApiStackProps) {
		super(scope, id, props);

		const { stage } = props;

		// CORS is now handled dynamically in Lambda functions to support
		// multi-tenant wildcard domains (*.domain.com)
		// See src/node/lib/cors.ts for the CORS configuration

		// Project name for API naming
		if (!process.env.PROJECT_NAME) {
			throw new Error("PROJECT_NAME environment variable is required");
		}
		const projectName = process.env.PROJECT_NAME;

		// Create HTTP API
		// Fine-grained CORS (multi-tenant wildcard domains) is handled in Lambda — see src/node/lib/cors.ts
		// Gateway-level corsPreflight is ALSO needed so that responses generated by API Gateway itself
		// (authorizer 401/403, throttle 429, gateway 5xx) carry CORS headers. Without this, browsers
		// see an opaque "CORS error" instead of the real status code when the authorizer rejects a token.
		this.httpApi = new apigwv2.HttpApi(this, "HttpApi", {
			apiName: `${projectName}-${props.stage}-api`,
			description: "Production-grade serverless HTTP API",
			// The execute-api endpoint must stay enabled because CloudFront uses it
			// as origin. HTTP API v2 does not support resource policies, so the raw
			// gateway URL bypasses the CloudFront WAF. Do not expose the execute-api
			// URL publicly; rely on CloudFront as the sole entry point.
			disableExecuteApiEndpoint: false,
			corsPreflight: {
				allowOrigins: (() => {
					if (!process.env.CORS_EXACT_ORIGINS) {
						throw new Error(
							"CORS_EXACT_ORIGINS environment variable is required",
						);
					}
					const origins = process.env.CORS_EXACT_ORIGINS.split(",")
						.map((o) => o.trim())
						.filter(Boolean);

					// Add wildcard subdomain patterns from CORS_PARENT_DOMAINS
					// so API Gateway preflight matches the same origins as Lambda CORS
					const parentDomains = (process.env.CORS_PARENT_DOMAINS || "")
						.split(",")
						.map((s) => s.trim())
						.filter((s) => s.includes("."));
					for (const pd of parentDomains) {
						origins.push(`https://*.${pd}`);
					}

					return origins;
				})(),
				allowMethods: [
					apigwv2.CorsHttpMethod.GET,
					apigwv2.CorsHttpMethod.POST,
					apigwv2.CorsHttpMethod.PUT,
					apigwv2.CorsHttpMethod.PATCH,
					apigwv2.CorsHttpMethod.DELETE,
					apigwv2.CorsHttpMethod.OPTIONS,
				],
				allowHeaders: [
					"Authorization",
					"Content-Type",
					"Idempotency-Key",
					"X-Requested-With",
					"X-API-Key",
					"X-Secret-Token",
					"X-Webhook-Signature",
					"X-Request-Id",
				],
				maxAge: cdk.Duration.minutes(10),
			},
		});

		// Configure API Gateway throttling (rate limiting)
		// Note: HTTP API v2 throttling is configured via the default stage
		const defaultStage = this.httpApi.defaultStage?.node
			.defaultChild as cdk.aws_apigatewayv2.CfnStage;
		if (defaultStage) {
			defaultStage.defaultRouteSettings = {
				throttlingBurstLimit: props.stage === "production" ? 2000 : 1000,
				throttlingRateLimit: props.stage === "production" ? 1000 : 500,
			};
		}

		// ============================================
		// WAF v2 — AWS Managed Rules for common threats
		// ============================================
		const webAcl = new wafv2.CfnWebACL(this, "ApiWebAcl", {
			name: `${projectName}-${props.stage}-api-waf`,
			scope: "CLOUDFRONT",
			defaultAction: { allow: {} },
			visibilityConfig: {
				cloudWatchMetricsEnabled: true,
				metricName: `${projectName}-${props.stage}-waf`,
				sampledRequestsEnabled: true,
			},
			rules: [
				// Block oversized request bodies on paths that don't need large payloads
				{
					name: "BodySizeLimitNonExemptPaths",
					priority: 0,
					action: { block: {} },
					statement: {
						andStatement: {
							statements: [
								{
									sizeConstraintStatement: {
										fieldToMatch: {
											body: { oversizeHandling: "MATCH" },
										},
										comparisonOperator: "GT",
										size: 8192,
										textTransformations: [{ priority: 0, type: "NONE" }],
									},
								},
								{
									notStatement: {
										statement: {
											orStatement: {
												statements: [
													{
														byteMatchStatement: {
															fieldToMatch: { uriPath: {} },
															positionalConstraint: "STARTS_WITH",
															searchString: "/v1/graphql",
															textTransformations: [
																{ priority: 0, type: "LOWERCASE" },
															],
														},
													},
													{
														byteMatchStatement: {
															fieldToMatch: { uriPath: {} },
															positionalConstraint: "STARTS_WITH",
															searchString: "/v1/media/",
															textTransformations: [
																{ priority: 0, type: "LOWERCASE" },
															],
														},
													},
													{
														byteMatchStatement: {
															fieldToMatch: { uriPath: {} },
															positionalConstraint: "STARTS_WITH",
															searchString: "/v1/webhooks/",
															textTransformations: [
																{ priority: 0, type: "LOWERCASE" },
															],
														},
													},
												],
											},
										},
									},
								},
							],
						},
					},
					visibilityConfig: {
						cloudWatchMetricsEnabled: true,
						metricName: "BodySizeLimitNonExempt",
						sampledRequestsEnabled: true,
					},
				},
				{
					name: "AWSManagedRulesCommonRuleSet",
					priority: 1,
					overrideAction: { none: {} },
					statement: {
						managedRuleGroupStatement: {
							vendorName: "AWS",
							name: "AWSManagedRulesCommonRuleSet",
							excludedRules: [
								// Globally excluded — the custom rule above enforces body-size limits on non-exempt paths
								{ name: "SizeRestrictions_BODY" },
							],
						},
					},
					visibilityConfig: {
						cloudWatchMetricsEnabled: true,
						metricName: "AWSCommonRules",
						sampledRequestsEnabled: true,
					},
				},
				{
					name: "AWSManagedRulesKnownBadInputsRuleSet",
					priority: 2,
					overrideAction: { none: {} },
					statement: {
						managedRuleGroupStatement: {
							vendorName: "AWS",
							name: "AWSManagedRulesKnownBadInputsRuleSet",
						},
					},
					visibilityConfig: {
						cloudWatchMetricsEnabled: true,
						metricName: "AWSKnownBadInputs",
						sampledRequestsEnabled: true,
					},
				},
				{
					name: "AWSManagedRulesSQLiRuleSet",
					priority: 3,
					overrideAction: { none: {} },
					statement: {
						managedRuleGroupStatement: {
							vendorName: "AWS",
							name: "AWSManagedRulesSQLiRuleSet",
						},
					},
					visibilityConfig: {
						cloudWatchMetricsEnabled: true,
						metricName: "AWSSQLInjection",
						sampledRequestsEnabled: true,
					},
				},
				{
					name: "RateLimitPerIP",
					priority: 4,
					action: { block: {} },
					statement: {
						rateBasedStatement: {
							limit: props.stage === "production" ? 2000 : 500,
							aggregateKeyType: "IP",
						},
					},
					visibilityConfig: {
						cloudWatchMetricsEnabled: true,
						metricName: "RateLimitPerIP",
						sampledRequestsEnabled: true,
					},
				},
			],
		});

		// WAF will be associated with CloudFront below — CfnWebACLAssociation is not used
		// because WAFv2 REGIONAL scope does not support HTTP API v2 directly.

		// Common Lambda environment variables
		const commonEnv = {
			PROJECT_NAME: projectName,
			NODE_ENV: props.stage === "production" ? "production" : "staging",
			STAGE: props.stage,
			// Public client ID (non-sensitive) — needed by authorizer to build JWKS URL
			WORKOS_CLIENT_ID: process.env.WORKOS_CLIENT_ID || "",
			// Secret ARNs — actual credentials fetched at runtime, never stored as plaintext env vars
			WORKOS_SECRET_ARN: props.workosSecret.secretArn,
			DB_SECRET_ARN: props.dbSecret.secretArn,
			// S3 and Media Configuration
			IMAGES_BUCKET: process.env.IMAGES_BUCKET || "",
			IMAGES_CDN_URL: process.env.IMAGES_CDN_URL || "",
			// CORS Configuration
			CORS_DOMAIN_PATTERNS: process.env.CORS_DOMAIN_PATTERNS || "",
			CORS_EXACT_ORIGINS: process.env.CORS_EXACT_ORIGINS || "",
			CORS_PARENT_DOMAINS: process.env.CORS_PARENT_DOMAINS || "",
			// Sentry Error Monitoring
			SENTRY_DSN: process.env.SENTRY_DSN || "",
			SENTRY_ENVIRONMENT: props.stage,
		};

		// Exact bucket name used for scoped IAM permissions (same logic as bucketName below)
		const iamBucketName =
			process.env.IMAGES_BUCKET ||
			(props.stage === "production"
				? `${projectName}-images-depot`
				: `${projectName}-images-depot-staging`);

		// Lambda execution role with consolidated permissions
		const lambdaRole = new iam.Role(this, "LambdaExecutionRole", {
			assumedBy: new iam.ServicePrincipal("lambda.amazonaws.com"),
			managedPolicies: [
				iam.ManagedPolicy.fromAwsManagedPolicyName(
					"service-role/AWSLambdaBasicExecutionRole",
				),
				iam.ManagedPolicy.fromAwsManagedPolicyName("AWSXRayDaemonWriteAccess"),
			],
			inlinePolicies: {
				LambdaServicePolicy: new iam.PolicyDocument({
					statements: [
						// Secrets Manager access
						new iam.PolicyStatement({
							effect: iam.Effect.ALLOW,
							actions: ["secretsmanager:GetSecretValue"],
							resources: [
								props.workosSecret.secretArn,
								props.dbSecret.secretArn,
							],
						}),
						// S3 access for image bucket (scoped to exact bucket name)
						new iam.PolicyStatement({
							effect: iam.Effect.ALLOW,
							actions: ["s3:PutObject", "s3:GetObject", "s3:DeleteObject"],
							resources: [`arn:aws:s3:::${iamBucketName}/*`],
						}),
						new iam.PolicyStatement({
							effect: iam.Effect.ALLOW,
							actions: ["s3:ListBucket"],
							resources: [`arn:aws:s3:::${iamBucketName}`],
						}),
					],
				}),
			},
		});

		// Get S3 bucket name from environment variable
		const bucketName =
			process.env.IMAGES_BUCKET ||
			(props.stage === "production"
				? `${projectName}-images-depot`
				: `${projectName}-images-depot-staging`);

		// ============================================
		// BLUE-GREEN DEPLOYMENT — CodeDeploy
		// Production: canary 10% for 5 min before full cutover, automatic rollback on errors.
		// Staging: immediate cutover (ALL_AT_ONCE) for fast iteration.
		// All handlers (Node.js, Python, authorizer) are wrapped with wrapWithBlueGreen().
		// ============================================
		const codeDeployApp = new codedeploy.LambdaApplication(
			this,
			"LambdaDeployApp",
			{
				applicationName: `${projectName}-${props.stage}-lambda-deploy`,
			},
		);

		const deploymentConfig =
			props.stage === "production"
				? codedeploy.LambdaDeploymentConfig.CANARY_10PERCENT_5MINUTES
				: codedeploy.LambdaDeploymentConfig.ALL_AT_ONCE;

		// Route builder — creates handlers and wraps each one in CodeDeploy blue-green.
		// All API Gateway integrations target the returned "live" alias, not the raw function.
		const routeBuilder = new RouteBuilder(
			this,
			commonEnv,
			lambdaRole,
			props.stage,
			codeDeployApp,
			deploymentConfig,
			props.alarmTopic,
		);

		// ============================================
		// WORKOS AUTHORIZER — blue-green wrapped
		// ============================================
		const workosAuthorizerFn = new lambdaNodejs.NodejsFunction(
			this,
			"WorkOSAuthorizer",
			{
				functionName: `${projectName}-${props.stage}-workos-authorizer`,
				entry: path.join(__dirname, "../../src/node/authorizers/workos-jwt.ts"),
				handler: "handler",
				runtime: lambda.Runtime.NODEJS_24_X,
				timeout: cdk.Duration.seconds(30),
				environment: commonEnv,
				tracing: lambda.Tracing.ACTIVE,
				bundling: {
					minify: true,
					sourceMap: false,
					target: "node24",
					format: lambdaNodejs.OutputFormat.CJS,
					mainFields: ["main", "module"],
				},
			},
		);

		const workosAuthorizerAlias = routeBuilder.wrapWithBlueGreen(
			workosAuthorizerFn,
			"WorkOSAuthorizer",
		);

		const customAuthorizer = new apigwv2Authorizers.HttpLambdaAuthorizer(
			"WorkOSAuthorizer",
			workosAuthorizerAlias,
			{
				authorizerName: `${props.stage}-workos-authorizer`,
				responseTypes: [apigwv2Authorizers.HttpLambdaResponseType.SIMPLE],
				// Cache valid tokens for 5 minutes to reduce Lambda invocations
				// Tokens are validated by signature, so caching is safe
				resultsCacheTtl: cdk.Duration.minutes(5),
			},
		);

		// Register route groups organized by authentication pattern
		// Public routes: health checks, webhooks (no auth, but with their own verification)
		new PublicRoutes(this, this.httpApi, routeBuilder);

		// Protected routes: media endpoints (require WorkOS JWT)
		new ProtectedRoutes(
			this,
			this.httpApi,
			routeBuilder,
			customAuthorizer,
			bucketName,
		);

		// Internal routes: reserved for service-to-service communication
		// Currently empty. When adding routes here, protect them with either:
		//   - The WorkOS authorizer, or
		//   - An API key via withCustomHeader, or
		//   - VPC-only access via resource policy
		new InternalRoutes(this, this.httpApi, routeBuilder);

		// Python test handler — only deployed in non-production environments
		if (stage !== "production") {
			const pythonTestFn = new lambda.Function(this, "PythonTestHandler", {
				functionName: `${projectName}-${props.stage}-python-test-handler`,
				runtime: lambda.Runtime.PYTHON_3_11,
				code: lambda.Code.fromAsset(path.join(__dirname, "../../src/python")),
				handler: "handlers.test.hello.handler",
				architecture: lambda.Architecture.ARM_64,
				memorySize: 256,
				timeout: cdk.Duration.seconds(5),
				environment: commonEnv,
				tracing: lambda.Tracing.ACTIVE,
				logRetention: undefined, // Disabled to avoid AWS rate limits
			});

			const pythonTestAlias = routeBuilder.wrapWithBlueGreen(
				pythonTestFn,
				"PythonTest",
			);

			this.httpApi.addRoutes({
				path: "/v1/test/python",
				methods: [apigwv2.HttpMethod.GET],
				integration: new apigwv2Integrations.HttpLambdaIntegration(
					"PythonTestIntegration",
					pythonTestAlias,
				),
			});
		}

		// Python user profile handler (invoked by TypeScript proxy)
		const pythonUserProfileFn = new lambda.Function(
			this,
			"PythonUserProfileHandler",
			{
				functionName: `${projectName}-${props.stage}-python-user-profile`,
				runtime: lambda.Runtime.PYTHON_3_11,
				code: lambda.Code.fromAsset(path.join(__dirname, "../../src/python")),
				handler: "handlers.users.profile.handler",
				architecture: lambda.Architecture.ARM_64,
				memorySize: 256,
				timeout: cdk.Duration.seconds(10),
				environment: commonEnv,
				tracing: lambda.Tracing.ACTIVE,
				logRetention: undefined,
			},
		);

		const pythonUserProfileAlias = routeBuilder.wrapWithBlueGreen(
			pythonUserProfileFn,
			"PythonUserProfile",
		);

		this.httpApi.addRoutes({
			path: "/v1/users/python-profile",
			methods: [apigwv2.HttpMethod.GET],
			integration: new apigwv2Integrations.HttpLambdaIntegration(
				"PythonProfileIntegration",
				pythonUserProfileAlias,
			),
			authorizer: customAuthorizer,
		});

		// Note: Throttling can be configured later via AWS Console if needed
		// API Gateway v2 throttling is managed differently than v1

		// ============================================
		// GRAPHQL HANDLER
		// ============================================
		const graphqlFn = new lambdaNodejs.NodejsFunction(this, "GraphQLHandler", {
			functionName: `${projectName}-${props.stage}-graphql`,
			entry: path.join(__dirname, "../../src/node/handlers/graphql/handler.ts"),
			handler: "handler",
			runtime: lambda.Runtime.NODEJS_24_X,
			architecture: lambda.Architecture.ARM_64,
			timeout: cdk.Duration.seconds(30),
			memorySize: 512,
			environment: commonEnv,
			role: lambdaRole,
			tracing: lambda.Tracing.ACTIVE,
			logRetention: undefined,
			bundling: {
				minify: true,
				sourceMap: props.stage === "development",
				externalModules: ["@aws-sdk/*"],
				commandHooks: {
					beforeBundling: (
						_inputDir: string,
						_outputDir: string,
					): string[] => [],
					afterBundling: (inputDir: string, outputDir: string): string[] => [
						`cp -r ${inputDir}/src/node/handlers/graphql/schema/*.graphql ${outputDir}/`,
					],
					beforeInstall: (
						_inputDir: string,
						_outputDir: string,
					): string[] => [],
				},
			},
		});

		const graphqlAlias = routeBuilder.wrapWithBlueGreen(graphqlFn, "GraphQL");

		// Add GraphQL route with WorkOS authorizer
		this.httpApi.addRoutes({
			path: "/v1/graphql",
			methods:
				props.stage === "development"
					? [apigwv2.HttpMethod.POST, apigwv2.HttpMethod.GET]
					: [apigwv2.HttpMethod.POST],
			integration: new apigwv2Integrations.HttpLambdaIntegration(
				"GraphQLIntegration",
				graphqlAlias,
			),
			authorizer: customAuthorizer,
		});

		// Output GraphQL endpoint
		new cdk.CfnOutput(this, "GraphQLEndpoint", {
			value: `${this.httpApi.url}v1/graphql`,
			description: "GraphQL API endpoint",
		});

		// ============================================
		// API GATEWAY HTTP API v2 ALARMS
		// Placed here (not in MonitoringStack) because HTTP API v2 metrics
		// require the ApiId dimension, which is only known after construct creation.
		// ============================================
		const apiId = this.httpApi.apiId;

		const apiRequestMetric = new cloudwatch.Metric({
			namespace: "AWS/ApiGateway",
			metricName: "Count",
			dimensionsMap: { ApiId: apiId },
			statistic: "Sum",
			period: cdk.Duration.minutes(5),
		});

		const api5xxMetric = new cloudwatch.Metric({
			namespace: "AWS/ApiGateway",
			metricName: "5xx",
			dimensionsMap: { ApiId: apiId },
			statistic: "Sum",
			period: cdk.Duration.minutes(5),
		});

		const api4xxMetric = new cloudwatch.Metric({
			namespace: "AWS/ApiGateway",
			metricName: "4xx",
			dimensionsMap: { ApiId: apiId },
			statistic: "Sum",
			period: cdk.Duration.minutes(5),
		});

		const api5xxAlarm = new cloudwatch.Alarm(this, "Api5xxAlarm", {
			alarmName: `${projectName}-${props.stage}-api-high-5xx-rate`,
			alarmDescription: "HTTP API 5xx error rate > 1%",
			metric: new cloudwatch.MathExpression({
				expression: "(m1/m2)*100",
				usingMetrics: { m1: api5xxMetric, m2: apiRequestMetric },
			}),
			threshold: 1,
			evaluationPeriods: 2,
			datapointsToAlarm: 2,
			comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
			treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
		});
		api5xxAlarm.addAlarmAction(
			new cloudwatchActions.SnsAction(props.alarmTopic),
		);

		const api4xxAlarm = new cloudwatch.Alarm(this, "Api4xxAlarm", {
			alarmName: `${projectName}-${props.stage}-api-high-4xx-rate`,
			alarmDescription: "HTTP API 4xx error rate > 10%",
			metric: new cloudwatch.MathExpression({
				expression: "(m1/m2)*100",
				usingMetrics: { m1: api4xxMetric, m2: apiRequestMetric },
			}),
			threshold: 10,
			evaluationPeriods: 2,
			datapointsToAlarm: 2,
			comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
			treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
		});
		api4xxAlarm.addAlarmAction(
			new cloudwatchActions.SnsAction(props.alarmTopic),
		);

		// ============================================
		// GRAPHQL DOCUMENTATION HANDLER (GraphiQL)
		// Only enabled in development/local, disabled in staging/production for security
		// ============================================
		if (
			props.stage === "development" ||
			props.stage === "dev" ||
			props.stage === "local"
		) {
			const graphqlDocsHandler = new lambdaNodejs.NodejsFunction(
				this,
				"GraphQLDocsHandler",
				{
					functionName: `${projectName}-${props.stage}-graphql-docs`,
					entry: path.join(
						__dirname,
						"../../src/node/handlers/graphql/docs.ts",
					),
					handler: "handler",
					runtime: lambda.Runtime.NODEJS_24_X,
					architecture: lambda.Architecture.ARM_64,
					timeout: cdk.Duration.seconds(10),
					memorySize: 256,
					environment: {
						STAGE: props.stage,
					},
					// reservedConcurrentExecutions removed - use unreserved pool
					bundling: {
						minify: true,
						sourceMap: false,
					},
				},
			);

			// Add GraphQL docs route (no auth required - development only)
			this.httpApi.addRoutes({
				path: "/graphql/docs",
				methods: [apigwv2.HttpMethod.GET],
				integration: new apigwv2Integrations.HttpLambdaIntegration(
					"GraphQLDocsIntegration",
					graphqlDocsHandler,
				),
				// No authorizer - development environment only
			});

			// Output GraphQL docs endpoint
			new cdk.CfnOutput(this, "GraphQLDocsEndpoint", {
				value: `${this.httpApi.url}graphql/docs`,
				description:
					"GraphQL interactive documentation (GraphiQL) - Development only",
			});
		}

		// ============================================
		// CLOUDFRONT DISTRIBUTION
		// WAFv2 doesn't support HTTP API v2 directly — CloudFront is required.
		// WAF (CLOUDFRONT scope) is attached here; stack must be in us-east-1.
		// ============================================

		// Resolve custom domain config before creating CloudFront so we can pass
		// certificate + domainNames at construction time (CloudFront requires this).
		let certificate: acm.ICertificate | undefined;
		let hostedZone: route53.IHostedZone | undefined;
		const apiDomain = process.env.API_DOMAIN;

		if (apiDomain) {
			const zoneName = process.env.HOSTED_ZONE_NAME;
			const certArn = process.env.API_CERT_ARN;

			if (zoneName && process.env.HOSTED_ZONE_ID) {
				hostedZone = route53.HostedZone.fromHostedZoneAttributes(
					this,
					"ApiHostedZone",
					{
						hostedZoneId: process.env.HOSTED_ZONE_ID,
						zoneName,
					},
				);
			}

			if (certArn) {
				// CloudFront requires the cert to be in us-east-1 — use an existing cert ARN from us-east-1
				certificate = acm.Certificate.fromCertificateArn(
					this,
					"ApiDomainCert",
					certArn,
				);
			} else if (hostedZone) {
				certificate = new acm.Certificate(this, "ApiDomainDnsCert", {
					domainName: apiDomain,
					validation: acm.CertificateValidation.fromDns(hostedZone),
				});
			}
		}

		// Origin: HTTP API execute-api URL (not the custom domain)
		const apiOriginDomain = `${this.httpApi.apiId}.execute-api.${this.region}.amazonaws.com`;

		const distribution = new cloudfront.Distribution(this, "ApiDistribution", {
			comment: `${projectName}-${props.stage} API`,
			defaultBehavior: {
				origin: new origins.HttpOrigin(apiOriginDomain, {
					protocolPolicy: cloudfront.OriginProtocolPolicy.HTTPS_ONLY,
				}),
				// Forward all methods (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS)
				allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
				// No caching — this is an API, all responses must be fresh
				cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
				// Forward all viewer headers except Host (use origin host for TLS)
				originRequestPolicy:
					cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
				viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
			},
			// Attach WAF (CLOUDFRONT scope) to this distribution
			webAclId: webAcl.attrArn,
			// Only serve from US/Canada/Europe edge nodes (cheapest tier)
			priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
			// Custom domain + cert (only set when API_DOMAIN is configured)
			...(certificate && apiDomain
				? { certificate, domainNames: [apiDomain] }
				: {}),
		});

		// Route53 alias record pointing to CloudFront (replaces previous API Gateway alias)
		if (hostedZone && apiDomain) {
			const recordName = apiDomain.endsWith(`.${hostedZone.zoneName}`)
				? apiDomain.slice(0, apiDomain.length - hostedZone.zoneName.length - 1)
				: apiDomain;

			new route53.ARecord(this, "ApiDomainAliasRecord", {
				zone: hostedZone,
				recordName,
				target: route53.RecordTarget.fromAlias(
					new route53targets.CloudFrontTarget(distribution),
				),
			});

			new cdk.CfnOutput(this, "CustomDomain", {
				value: `https://${apiDomain}`,
				description: "Custom API domain (via CloudFront)",
			});
		}

		new cdk.CfnOutput(this, "CloudFrontDomain", {
			value: `https://${distribution.distributionDomainName}`,
			description: "CloudFront distribution domain",
		});

		new cdk.CfnOutput(this, "CloudFrontDistributionId", {
			value: distribution.distributionId,
			description: "CloudFront distribution ID",
		});

		// Output API endpoint
		new cdk.CfnOutput(this, "ApiEndpoint", {
			value: this.httpApi.url!,
			description: "HTTP API endpoint URL",
		});

		// ============================================
		// SCHEDULED MAINTENANCE — Idempotency Key Cleanup
		// Runs daily to purge expired idempotency keys
		// ============================================
		const janitorHandler = routeBuilder.createHandler({
			name: "IdempotencyJanitor",
			path: "handlers/utils/janitor.ts",
			memorySize: 256,
			timeout: cdk.Duration.seconds(60),
		});

		new events.Rule(this, "JanitorSchedule", {
			ruleName: `${projectName}-${stage}-janitor-daily`,
			schedule: events.Schedule.rate(cdk.Duration.days(1)),
			targets: [new eventsTargets.LambdaFunction(janitorHandler)],
		});

		// Apply LogRetention aspect -- visit() applies retention during the prepare phase
		Aspects.of(this).add(new LogRetentionAspect(stage));
	}
}
