export const GRAPHQL_SAFE_ERROR_CODES = new Set([
	"BAD_USER_INPUT",
	"GRAPHQL_VALIDATION_FAILED",
	"GRAPHQL_PARSE_FAILED",
	"FORBIDDEN",
	"UNAUTHENTICATED",
	"NOT_FOUND",
	"CONFLICT",
]);

export const GRAPHQL_CLIENT_ERROR_CODES = new Set([
	...GRAPHQL_SAFE_ERROR_CODES,
	"PERSISTED_QUERY_NOT_FOUND",
]);
